/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package project.hr;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLDataException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class add_info extends javax.swing.JFrame {

    String Fist_name;
    String Last_name;
    String Department;
    String Position;
    String Gender;
    String Nationality;
    String Birthday;
    String Salary;
    String ID;
    private String query;
    private PreparedStatement ss;
    
    /** Creates new form Employee_information */
    public add_info() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Tf_name = new javax.swing.JTextField();
        jf_name = new javax.swing.JLabel();
        jlast_name = new javax.swing.JLabel();
        Tlast_name = new javax.swing.JTextField();
        Tid = new javax.swing.JTextField();
        jid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdepartment = new javax.swing.JLabel();
        Tdepartment = new javax.swing.JTextField();
        Tposition = new javax.swing.JTextField();
        jposition = new javax.swing.JLabel();
        Tsalary = new javax.swing.JTextField();
        jsalary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbirthday = new javax.swing.JLabel();
        jgender = new javax.swing.JLabel();
        jnationality = new javax.swing.JLabel();
        Tnationality = new javax.swing.JTextField();
        Tgender = new javax.swing.JTextField();
        Tbirthday = new javax.swing.JTextField();
        jADD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_nameActionPerformed(evt);
            }
        });
        jPanel7.add(Tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        jf_name.setText("First Name :");
        jPanel7.add(jf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jlast_name.setText("Last Name :");
        jPanel7.add(jlast_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        Tlast_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tlast_nameActionPerformed(evt);
            }
        });
        jPanel7.add(Tlast_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 66, -1));

        Tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidActionPerformed(evt);
            }
        });
        jPanel7.add(Tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 70, -1));

        jid.setText("ID :");
        jPanel7.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Current Position");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jdepartment.setText("Department :");
        jPanel7.add(jdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        Tdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdepartmentActionPerformed(evt);
            }
        });
        jPanel7.add(Tdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 76, -1));

        Tposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpositionActionPerformed(evt);
            }
        });
        jPanel7.add(Tposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 76, -1));

        jposition.setText("Position :");
        jPanel7.add(jposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Tsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsalaryActionPerformed(evt);
            }
        });
        jPanel7.add(Tsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, -1));

        jsalary.setText("Salary :");
        jPanel7.add(jsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ADD NEW EMPLOYEE");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Personal Information");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jbirthday.setText("Birthday :");
        jPanel7.add(jbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jgender.setText("Gender :");
        jPanel7.add(jgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jnationality.setText("Nationality :");
        jPanel7.add(jnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));
        jPanel7.add(Tnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 75, -1));
        jPanel7.add(Tgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 80, -1));
        jPanel7.add(Tbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 75, -1));

        jADD.setText("ADD");
        jADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jADDActionPerformed(evt);
            }
        });
        jPanel7.add(jADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 65, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/add.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 550, 390));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 490, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdepartmentActionPerformed

    private void TsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsalaryActionPerformed

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void Tlast_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tlast_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tlast_nameActionPerformed

    private void jADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jADDActionPerformed
      try{
        Fist_name=Tf_name.getText().toString();
        Last_name=Tlast_name.getText().toString();
        Department=Tdepartment.getText().toString();
        Position=Tposition.getText().toString();
        Gender=Tgender.getText().toString();
        Nationality=Tnationality.getText().toString();
        Birthday=Tbirthday.getText().toString();
        Salary=Tsalary.getText().toString();
        ID=Tid.getText().toString();
        
       DBIN cc = new DBIN(); 
        Connection c=cc.conncet();
          query="insert into employees values('"+Fist_name+"','"+Last_name+"','"+Department+"','"+Position+"','"+Gender+"','"+Nationality+"','"+Birthday+"','"+Salary+"','"+ID+"')";
          ss=c.prepareStatement(query);
           ss.execute(query);
           JOptionPane.showMessageDialog(null,"your add new empployee");
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null,"you diden't put data ");
          
      }
       
        
        
        
    }//GEN-LAST:event_jADDActionPerformed

    private void Tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_nameActionPerformed

    private void TpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpositionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tbirthday;
    private javax.swing.JTextField Tdepartment;
    private javax.swing.JTextField Tf_name;
    private javax.swing.JTextField Tgender;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tlast_name;
    private javax.swing.JTextField Tnationality;
    private javax.swing.JTextField Tposition;
    private javax.swing.JTextField Tsalary;
    private javax.swing.JButton jADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jbirthday;
    private javax.swing.JLabel jdepartment;
    private javax.swing.JLabel jf_name;
    private javax.swing.JLabel jgender;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jlast_name;
    private javax.swing.JLabel jnationality;
    private javax.swing.JLabel jposition;
    private javax.swing.JLabel jsalary;
    // End of variables declaration//GEN-END:variables

}
