/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.hr;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLDataException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Registration_page extends javax.swing.JFrame {
    String uesrname;
        String pass;
        String age;
        String phone;
        String sex;
        String id;
    private String query;
    private PreparedStatement ss;
    public Registration_page() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tpass1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tphone = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        female = new javax.swing.JCheckBox();
        male = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        Tname4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("phone :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 120, 60, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Age :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 200, 50, 22);

        Tpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tpass1ActionPerformed(evt);
            }
        });
        getContentPane().add(Tpass1);
        Tpass1.setBounds(180, 152, 170, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 160, 90, 22);

        Tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TphoneActionPerformed(evt);
            }
        });
        getContentPane().add(Tphone);
        Tphone.setBounds(180, 112, 170, 30);

        Tage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TageActionPerformed(evt);
            }
        });
        getContentPane().add(Tage);
        Tage.setBounds(180, 192, 170, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("sex :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 50, 22);

        jButton1.setText("Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 300, 113, 38);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 40, 40, 22);

        Tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidActionPerformed(evt);
            }
        });
        getContentPane().add(Tid);
        Tid.setBounds(180, 32, 170, 30);

        buttonGroup1.add(female);
        female.setText("female");
        getContentPane().add(female);
        female.setBounds(280, 240, 80, 23);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        male.setText("male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(190, 240, 70, 23);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 80, 90, 22);

        Tname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tname4ActionPerformed(evt);
            }
        });
        getContentPane().add(Tname4);
        Tname4.setBounds(180, 72, 170, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/perspectives-human-resource-management-recruiting-companions.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 590, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tpass1ActionPerformed

    private void TphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TphoneActionPerformed

    private void TageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            id=Tid.getText().toString();
             uesrname = Tname4.getText().toString();
             pass=Tpass1.getText().toString();
             age=Tage.getText().toString();
             phone=Tphone.getText().toString();
             
             if(male.isSelected()){
                 sex="male";
                 
                 
             }else if(female.isSelected()){
                 sex="female";
             }
            DBIN cc = new DBIN();
            Connection c=cc.conncet();
            query="insert into logindatabase values('"+id+"','"+uesrname+"','"+pass+"','"+age+"','"+sex+"','"+phone+"')";
            ss=c.prepareStatement(query);
            ss.execute(query);
            JOptionPane.showMessageDialog(null,"your regsterg now");
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"you diden't put data ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void Tname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tname4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tname4;
    private javax.swing.JTextField Tpass1;
    private javax.swing.JTextField Tphone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox male;
    // End of variables declaration//GEN-END:variables
}
